### ISSUE TITLE
Can't Compile with Rust 0.13.0

### ISSUE THREAD

**Issue by fribeiro1** [zslayton/stomp-rs#39]
I am getting the following error when compiling with 0.13.0:

src\connection.rs:91:22: 91:97 error: mismatched types: expected `core::option::Option<collections::string::String>`, found `core::result::Result<collections::string::String, core::str::Utf8Error>` (expected enum core::option::Option, found enum core::result::Result)
src\connection.rs:91              detail: from_utf8(connected_frame.body.as_slice()).map(|err: &str| err.to_string())
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src\frame.rs:60:7: 60:18 error: mismatched types: expected `core::result::Result<&str, core::str::Utf8Error>`, found `core::option::Option<_>` (expected enum core::result::Result, found enum core::option::Option)
src\frame.rs:60       Some(ref s) => *s,
                      ^~~~~~~~~~~
src\frame.rs:61:7: 61:11 error: mismatched types: expected `core::result::Result<&str, core::str::Utf8Error>`, found `core::option::Option<_>` (expected enum core::result::Result, found enum core::option::Option)
src\frame.rs:61       None => "<Binary content>" // Space is wasted in this case. Could shrink to fit?
                      ^~~~
error: aborting due to 3 previous errors
Could not compile `stomp`.

Please advise.

**Comment by zslayton** [comment]
Sorry for the delayed reply, I was traveling for the holidays.

It would appear that `str`'s `from_utf8` function [now returns](http://doc.rust-lang.org/std/str/fn.from_utf8.html) a `Result` rather than an `Option`. There are a handful of other upstream compiler changes I need to catch up with as well. I'll put out a release in the next day or two to fix this. Thanks for the heads up!

**Comment by fribeiro1** [comment]
No problems! I will keep the ticket opened for tracking.

**Comment by zslayton** [comment]
Thanks. Upon further review, there were some other upstream changes that I'll need to catch up with as well. I'll try to do all that this week.

**Comment by fribeiro1** [comment]
Thanks, I will be looking forward to it.

**Comment by zslayton** [comment]
I found some time to work on it this evening. Version 0.3.6 on crates.io should resolve the problem. Please update your Cargo.toml and let me know if that fixes it for you.

**Comment by zslayton** [comment]
I'm going to go ahead and close this issue for now. Please feel free to reopen it if you continue to experience this issue while using the same version of the compiler. The latest nightly build of `rustc` introduced another set of breaking changes, so I have new things to fix. :)

**Comment by fribeiro1** [comment]
It is still failing, now with the following error:

src\session.rs:6:23: 6:29 error: unresolved import `std::sync::mpsc::Sender`. Co
uld not find `mpsc` in `std::sync`
src\session.rs:6 use std::sync::mpsc::{Sender, Receiver, channel};
                                       ^~~~~~
src\session.rs:6:31: 6:39 error: unresolved import `std::sync::mpsc::Receiver`.
Could not find `mpsc` in `std::sync`
src\session.rs:6 use std::sync::mpsc::{Sender, Receiver, channel};
                                               ^~~~~~~~
src\session.rs:6:41: 6:48 error: unresolved import `std::sync::mpsc::channel`. C
ould not find `mpsc` in `std::sync`
src\session.rs:6 use std::sync::mpsc::{Sender, Receiver, channel};
                                                         ^~~~~~~
error: aborting due to 3 previous errors
Could not compile `stomp`.

Please advise.
